### ISSUE TITLE
"When launching a web app" feels handwavy

### ISSUE THREAD

**Issue by yoavweiss** [WICG/web-app-launch#67]
It seems like this is the entry point to the spec's algorithms, and it's not well defined when that happens.
This seems like a concept that should be defined in HTML, and which would then call this spec explicitly from there.

Such a concept may also be useful for https://github.com/w3c/navigation-timing/issues/180

/cc @domenic

**Comment by alancutter** [comment]
This spec is essentially defining a `LaunchWebApp(appId, launchParams)` function for other specs/the user agent's OS integrations to use. Defining all the "callsites" is out of scope for this spec.

**Comment by yoavweiss** [comment]
I'm not saying you need to define the callsites as part of this spec. But I do think you need to file PRs on other specs that should be hooking into this. Otherwise, it's unclear when this is triggered.

**Comment by alancutter** [comment]
Yes, absolutely.
Specs to update:
- https://www.w3.org/TR/appmanifest/#launching-a-shortcut
- https://w3c.github.io/web-share-target/#launching-the-web-share-target
- https://wicg.github.io/manifest-incubations/index.html#launching-the-new_note_url
- https://wicg.github.io/manifest-incubations/index.html#handling-a-protocol-launch
- https://wicg.github.io/manifest-incubations/index.html#execute-a-file-handler-launch

**Comment by alancutter** [comment]
Updating https://w3c.github.io/web-share-target/#launching-the-web-share-target requires resolving https://github.com/WICG/web-app-launch/issues/62 so creating a new top-level browsing context has sufficient information to run a POST navigation.
