### ISSUE TITLE
"Containing relevant launch information" should be well-defined

### ISSUE THREAD

**Issue by yoavweiss** [WICG/web-app-launch#68]
Instead of that phrase at [launching a web app](https://wicg.github.io/sw-launch/#launching-a-web-app) we should define an algorithm that initializes a LaunchParams object, and defines its values.

**Comment by alancutter** [comment]
Initialising the LaunchParams object will be up to the different launch triggers e.g. share target or file handler, it's a parameter to this algorithm. "containing relevant launch information" should probably be non-normative text instead.

**Comment by yoavweiss** [comment]
I don't think it should be non-normative, but instead we need to define those concepts, if they aren't defined elsewhere.

/cc @mgiuca @dmurph @chasephillips for thoughts

**Comment by alancutter** [comment]
I'm not sure of a way to say "containing relevant launch information" in normative text and I don't think it's actually necessary to state. The LaunchParams is just an input parameter to the algorithm and if the caller has a good reason to include irrelevant launch information that's fine. 
Do you think it's okay to delete this phrasing and just resolve https://github.com/WICG/sw-launch/issues/67 ?

**Comment by yoavweiss** [comment]
Getting LaunchParams as input makes sense. Then it's on the callers you mentioned in https://github.com/WICG/sw-launch/issues/67#issuecomment-1288381141 to strictly define the relevant ones.

**Comment by alancutter** [comment]
This will be fixed as part of: https://github.com/WICG/web-app-launch/issues/67
