### ISSUE TITLE
"Process unconsumed launch params" call where there's no potential launch consumer

### ISSUE THREAD

**Issue by yoavweiss** [WICG/web-app-launch#70]
In [Launching a web app](https://wicg.github.io/sw-launch/#launching-a-web-app) it's unclear why step 4 is there. Is there a scenario where there's already an assigned launch consumer at that point?

**Comment by alancutter** [comment]
Yes, if we're in the `"launch_handler": { "client_mode": "focus-existing" }` flow where an app window is reused.
Example: https://sulky-lopsided-bean.glitch.me/brown/
Is this case worth pointing out in non-normative text?

**Comment by yoavweiss** [comment]
OK, cool. Yeah, seems worthwhile to point out that case in a note.
